name: Documentation

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]
      - name: Generate Docs
        run: |
          make gen-docs
          touch docs/_build/html/.nojekyll
      - name: Publish Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/html/ # The folder the action should deploy.
