name: Manual Get next update and verify dates

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: Start Date (YYYY-MM-DD)
        required: true
      end_date:
        description: End Date (YYYY-MM-DD)
        required: true

jobs:
  get_next_uv_dates:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]
      - name: Decrypt Google API secret
        run: ./.github/scripts/decrypt_google_api_secret.sh
        env:
          GOOGLE_API_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_API_SECRET_PASSPHRASE }}
      - name: Get next uv dates
        run: |
          get_next_uv_dates -msi ${{ secrets.PRODUCTION_MASTER_SPREADSHEET_ID }} -gacp $HOME/secrets/google-api-credentials.json -sd ${{ github.event.inputs.start_date }} -ed ${{ github.event.inputs.end_date }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: get-next-uv-dates-artifact
          path: next_uv_dates.csv
