name: Manual Run External Link Checker

on:
  workflow_dispatch:
    inputs:
      spreadsheet_ids:
        description: Spreadsheet Ids (delimited by comma)
        required: true

jobs:
  external_link_checker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install --upgrade pip==24.0 setuptools==70.0.0 wheel==0.43.0
          pip install .[all]
      - name: Decrypt Google API secret
        run: ./.github/scripts/decrypt_google_api_secret.sh
        env:
          GOOGLE_API_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_API_SECRET_PASSPHRASE }}
      - name: Run External Link Checker
        run: |
          run_external_link_checker -ssi ${{ github.event.inputs.spreadsheet_ids }} -gacp $HOME/secrets/google-api-credentials.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: external-link-artifact
          path: external_links.csv
