name: Manual Run Production Pipeline

on:
  issues:
    types: [opened]

jobs:
  authorization_and_correct_label:
    if: ${{ contains(github.event.issue.labels.*.name, 'Run Production Pipeline') }}
    runs-on: ubuntu-latest
    steps:
    - name: Authorization check
      uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pipeline:
    needs: [authorization_and_correct_label]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install .[all]
    - name: Run Staging Pipeline
      run: |
        my_example -ce ${{ secrets.GA_CLIENT_EMAIL }} -ci ${{ secrets.GA_CLIENT_ID }} -ccu ${{ secrets.GA_CLIENT_CERT_URL }} -pk ${{ secrets.GA_PRIVATE_KEY }} -pki ${{ secrets.GA_PRIVATE_KEY_ID }} -pi ${{ secrets.GA_PROJECT_ID }} -dbcu ${{ secrets.PRODUCTION_DB_CONNECTION_URL }}

