name: Manual Run Production Pipeline

on:
  issues:
    types: [opened]

jobs:
  authorization_and_correct_label:
    if: ${{ contains(github.event.issue.labels.*.name, 'Run Production Pipeline') }}
    runs-on: ubuntu-latest
    steps:
    - name: Authorization check
      uses: octokit/request-action@v2.0.0
      with:
        route: GET /repos/:repository/collaborators/${{ github.actor }}
        repository: ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pipeline:
    needs: [authorization_and_correct_label]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install .[all]
    - uses: actions/checkout@v2
    - name: Decrypt Google API secret
      run: ./.github/scripts/decrypt_google_api_secret.sh
      env:
        GOOGLE_API_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_API_SECRET_PASSPHRASE }}
    - name: Run Production Pipeline
      run: |
        run_sigla_pipeline -msi ${{ secrets.PRODUCTION_MASTER_SPREADSHEET_ID }} -gacp $HOME/secrets/google-api-credentials.json -dbcu ${{ secrets.PRODUCTION_DB_CONNECTION_URL }}

