name: Manual Run QA Test

on:
  workflow_dispatch:
    inputs:
      spreadsheet_ids:
        description: Spreadsheet Ids (delimited by comma)
        required: true
      db_env:
        description: Database Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  run_qa_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install --upgrade pip==24.0 setuptools==70.0.0 wheel==0.43.0
          pip install .[all]
      - name: Decrypt Google API secret
        run: ./.github/scripts/decrypt_google_api_secret.sh
        env:
          GOOGLE_API_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_API_SECRET_PASSPHRASE }}
      - name: Create tmp dir
        run: mkdir -p tmp
      - name: Run QA Test
        run: |
          run_qa_test  -gacp $HOME/secrets/google-api-credentials.json -ssi ${{ github.event.inputs.spreadsheet_ids }} -dbe ${{ github.event.inputs.db_env }} -sdbcu ${{ secrets.STAGING_DB_CONNECTION_URL }} -pdbcu ${{ secrets.PRODUCTION_DB_CONNECTION_URL }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qa-test-artifact
          path: qa-test.zip
