name: Manual Run Data Pipeline

on:
  workflow_dispatch:
    inputs:
      master_spreadsheet_id:
        description: Main Spreadsheet Id
        required: true
      db_env:
        description: Database Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production

jobs:
  run_sigla_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]
      - name: Decrypt Google API secret
        run: ./.github/scripts/decrypt_google_api_secret.sh
        env:
          GOOGLE_API_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_API_SECRET_PASSPHRASE }}
      - name: Run Data Pipeline
        run: |
          run_sigla_pipeline -gacp $HOME/secrets/google-api-credentials.json -msi ${{ github.event.inputs.master_spreadsheet_id }} -dbe ${{ github.event.inputs.db_env }} -sdbcu ${{ secrets.STAGING_DB_CONNECTION_URL }} -pdbcu ${{ secrets.PRODUCTION_DB_CONNECTION_URL }}
      - name: Create tmp dir
        if: ${{ success() }}
        run: mkdir -p tmp
      - name: Run QA Test
        if: ${{ success() }}
        run: |
          run_qa_test  -gacp $HOME/secrets/google-api-credentials.json -msi ${{ github.event.inputs.master_spreadsheet_id }} -dbe ${{ github.event.inputs.db_env }} -sdbcu ${{ secrets.STAGING_DB_CONNECTION_URL }} -pdbcu ${{ secrets.PRODUCTION_DB_CONNECTION_URL }}
      - name: Upload QA Test Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: qa-test-artifact
          path: qa-test.zip
