name: Run Staging Pipeline

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 7 * * 0'

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Dependencies
      run: |
        pip install --upgrade pip setuptools wheel
        pip install .[all]
    - uses: actions/checkout@v2
    - name: Decrypt Google API secret
      run: ./.github/scripts/decrypt_google_api_secret.sh
      env:
        GOOGLE_API_SECRET_PASSPHRASE: ${{ secrets.GOOGLE_API_SECRET_PASSPHRASE }}
    - name: Run Staging Pipeline
      run: |
        run_sigla_pipeline -msi ${{ secrets.STAGING_MASTER_SPREADSHEET_ID }} -gacp $HOME/secrets/google-api-credentials.json -dbcu ${{ secrets.STAGING_DB_CONNECTION_URL }}

